const express = require("express");
require("dotenv").config();
const app = express();
const bodyParser = require("body-parser");
const router = require("./src/routes/loansRoute");
const port = process.env.PORT || 3030;
app.use(express.json());
app.use(router);
app.use(bodyParser.json());
app.listen(port, () => console.log(`Server running on port ${port}`));
